version: '3.7'

services:
  weather-forecast-database:
    image: mongo
    container_name: weather-forecast-database
    environment:
      - ALLOW_EMPTY_PASSWORD=no
      - MONGODB_USERNAME=docker
      - MONGODB_PASSWORD=docker
      - MONGODB_DATABASE=weather-forecast
    ports:
      - '16017:27017'
    volumes:
      - weather-forecast-data:/data/db
    # networks:
    #   - weather-forecast-network

  weather-forecast-redis:
    image: redis
    container_name: weather-forecast-redis
    ports:
      - '6379:6379'
    volumes:
      - weather-forecast-data:/bitnami/redis/data
    # networks:
    #   - bulk-message-network

volumes:
  weather-forecast-data:
    driver: local
# networks:
#   weather-forecast-network:
#     driver: bridge
#     ipam:
#       config:
#         - subnet: 172.16.57.0/24
