version: '3.7'

services:
  app:
    build:
      context: .
    container_name: waves-points-api
    depends_on:
      - waves-points-database
      - waves-points-redis
    volumes:
      - .:/home/node/app
    ports:
      - ${APP_PORT}:${APP_PORT}
      - ${APP_PORT_DEBUG}:${APP_PORT_DEBUG}
    networks:
      - waves-points-network

  waves-points-database:
    image: mongo
    container_name: waves-points-database
    environment:
      - ALLOW_EMPTY_PASSWORD=no
      - MONGODB_USERNAME=${MONGO_USER}
      - MONGODB_PASSWORD=${MONGO_PASS}
      - MONGODB_DATABASE=${MONGO_DB}
    ports:
      - ${MONGO_PORT}:${MONGO_PORT}
    volumes:
      - waves-points-data:/data/db
    networks:
      - waves-points-network

  waves-points-redis:
    image: redis
    container_name: waves-points-redis
    ports:
      - ${REDIS_PORT}:${REDIS_PORT}
    volumes:
      - waves-points-data:/bitnami/redis/data
    networks:
      - waves-points-network

volumes:
  waves-points-data:
    driver: local

networks:
  waves-points-network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.16.57.0/24
